fix: qemu start issues and coredumps setup as soon as ssh becomes available (#6513)
https://github.com/ydb-platform/nbs/actions/runs/29310073358/job/87012299709
here we encountered error where test failed by timeout and we failed to
setup_coredumps and it looped processing of coredumps indefinetely. And
said coredumps processing were failing because ssh was not set up
correctly because it missed setting up environment variables.

```
  File "cloud/storage/core/tools/testing/qemu/lib/common.py", line 65, in get_command
    logger.info("ssh execute command: '{}'".format(" ".join(cmd)))
                                                   ^^^^^^^^^^^^^
TypeError: sequence item 17: expected str instance, NoneType found
```

So technically there are separate issues that cumulatively caused all
this:
1. _prepare_test_environment failed on `touch /mnt/fs0/.test` due to
crash in filestore-vhost
2. Setting up environment file didn't set envvars inside the running
recipe process. This lead to NoneType (which was referencing
QEMU_SSH_KEY) which lead to ssh failing infinitely.
3. Qemu started but QMP client failed and recipe didn't have pid file to
stop it. This lead to leaking of qemu processes (this is kind of side
issue)