[Filestore] fix linkage error after #4283 (#4313)
Error was introduced in #4283.
When building with `-D FORCE_STATIC_LINKING=yes` we get:
```
ld.lld: error: duplicate symbol: fuse_reply_none
>>> defined at fuse_lowlevel.c:304 (/home/svartmetal/nbs-github2/contrib/libs/virtiofsd/fuse_lowlevel.c:304)
>>>            fuse_lowlevel.c.o:(fuse_reply_none) in archive contrib/libs/virtiofsd/static/libvirtiofsd.a
>>> defined at fuse_virtio.c:373 (/home/svartmetal/nbs-github2/cloud/filestore/libs/vfs_fuse/vhost/fuse_virtio.c:373)
>>>            fuse_virtio.c.o:(.text.fuse_reply_none+0x0) in archive cloud/filestore/libs/vfs_fuse/vhost/liblibs-vfs_fuse-vhost.a
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
```