Fix FastShard impl/model build with stub (#7056)
### Notes

Fix the FastShard build with support param `FORCE_FASTSHARD_IPC_STUB`

- use silk-dependent `model` only when the existing IPC-stub condition
is disabled
- register the model unit-test directory with `RECURSE_FOR_TESTS`

### Issue
Fixes the FastShard build and configure failure in the Arcadia

```
In file included from $(SOURCE_ROOT)/cloud/filestore/libs/storage/fastshard/impl/model/handle_table.cpp:1:
In file included from $(SOURCE_ROOT)/cloud/filestore/libs/storage/fastshard/impl/model/handle_table.h:4:
$(SOURCE_ROOT)/cloud/filestore/libs/storage/fastshard/impl/model/persistent_hash_table.h:9:10: fatal error: 'silk/util/logger.h' file not found
    9 | #include <silk/util/logger.h>
      |          ^~~~~~~~~~~~~~~~~~~~
1 error generated.
```

```
PEERDIR to missing directory: $S/contrib/libs/silk/src/fibers

could not resolve include file: silk/fibers/mutex.h included from here: $S/cloud/filestore/libs/storage/fastshard/impl/model/page_store.cpp

could not resolve include file: silk/util/logger.h included from here: $S/cloud/filestore/libs/storage/fastshard/impl/model/page_store.cpp

could not resolve include file: silk/util/logger.h included from here: $S/cloud/filestore/libs/storage/fastshard/impl/model/persistent_bitmap.cpp

could not resolve include file: silk/util/logger.h included from here: $S/cloud/filestore/libs/storage/fastshard/impl/model/persistent_hash_table.h
```