fix std::mutex usage with include in server_ut.cpp (#6536)
### Notes
Fixes the new `journalled_device_tcp_server` unit test build by
including `<mutex>` in `server_ut.cpp`. The test uses `std::mutex` and
`std::unique_lock`, but the corresponding standard header was missing.


### Issue
```
$(SOURCE_ROOT)/cloud/storage/core/libs/journalled_device_tcp_server/server_ut.cpp:396:14: error: no type named 'mutex' in namespace 'std'
  396 |         std::mutex mutex;
      |         ~~~~~^
$(SOURCE_ROOT)/cloud/storage/core/libs/journalled_device_tcp_server/server_ut.cpp:405:33: error: expected ';' after expression
  405 |                 std::unique_lock lock(mutex);
      |                                 ^
      |                                 ;
$(SOURCE_ROOT)/cloud/storage/core/libs/journalled_device_tcp_server/server_ut.cpp:405:22: error: no member named 'unique_lock' in namespace 'std'; did you mean 'unique_copy'?
  405 |                 std::unique_lock lock(mutex);
      |                 ~~~~~^~~~~~~~~~~
      |                      unique_copy
$(SOURCE_ROOT)/contrib/libs/cxxsupp/libcxx/include/__algorithm/unique_copy.h:102:1: note: 'unique_copy' declared here
  102 | unique_copy(_InputIterator __first, _InputIterator __last, _OutputIterator __result, _BinaryPredicate __pred) {
      | ^
$(SOURCE_ROOT)/cloud/storage/core/libs/journalled_device_tcp_server/server_ut.cpp:405:17: error: reference to overloaded function could not be resolved; did you mean to call it?
  405 |                 std::unique_lock lock(mutex);
      |                 ^~~~~~~~~~~~~~~~
$(SOURCE_ROOT)/contrib/libs/cxxsupp/libcxx/include/__type_traits/invoke.h:146:10: note: in instantiation of function template specialization 'NCloud::NJournalled::NTestSuiteTDeviceTCPServerTest::TTestCaseShouldDispatchRequestsToBackend::Execute_(NUnitTest::TTestContext &)::(anonymous class)::operator()<NCloud::NProto::TAcquireDevicesRequest>' requested here
  146 | decltype(std::declval<_Fp>()(std::declval<_Args>()...))
      |          ^
$(SOURCE_ROOT)/contrib/libs/cxxsupp/libcxx/include/__type_traits/invoke.h:156:19: note: while substituting deduced template arguments into function template '__invoke' [with _Fp = (lambda at $(SOURCE_ROOT)/cloud/storage/core/libs/journalled_device_tcp_server/server_ut.cpp:403:13) &, _Args = <NCloud::NProto::TAcquireDevicesRequest>]
  156 |   static decltype(std::__invoke(std::declval<_XFp>(), std::declval<_XArgs>()...)) __try_call(int);
      |                   ^
$(SOURCE_ROOT)/contrib/libs/cxxsupp/libcxx/include/__type_traits/invoke.h:162:28: note: while substituting deduced template arguments into function template '__try_call' [with _XFp = (lambda at $(SOURCE_ROOT)/cloud/storage/core/libs/journalled_device_tcp_server/server_ut.cpp:403:13) &, _XArgs = (no value)]
  162 |   using _Result = decltype(__try_call<_Fp, _Args...>(0));
      |                            ^
$(SOURCE_ROOT)/contrib/libs/cxxsupp/libcxx/include/__type_traits/conjunction.h:28:32: note: in instantiation of template class 'std::__invokable_r<void, (lambda at $(SOURCE_ROOT)/cloud/storage/core/libs/journalled_device_tcp_server/server_ut.cpp:403:13) &, NCloud::NProto::TAcquireDevicesRequest>' requested here
   28 | __expand_to_true<__enable_if_t<_Pred::value>...> __and_helper(int);
      |                                ^
$(SOURCE_ROOT)/contrib/libs/cxxsupp/libcxx/include/__type_traits/conjunction.h:39:39: note: while substituting explicitly-specified template arguments into function template '__and_helper' 
   39 | using _And _LIBCPP_NODEBUG = decltype(std::__and_helper<_Pred...>(0));
      |                                       ^
$(SOURCE_ROOT)/contrib/libs/cxxsupp/libcxx/include/__functional/function.h:837:20: note: in instantiation of template type alias '_And' requested here
  837 |             bool = _And< _IsNotSame<__remove_cvref_t<_Fp>, function>, __invokable<_Fp, _ArgTypes...> >::value>
      |                    ^
$(SOURCE_ROOT)/contrib/libs/cxxsupp/libcxx/include/__functional/function.h:850:49: note: in instantiation of default argument for '__callable<(lambda at $(SOURCE_ROOT)/cloud/storage/core/libs/journalled_device_tcp_server/server_ut.cpp:403:13) &>' required here
  850 |   using _EnableIfLValueCallable = __enable_if_t<__callable<_Fp&>::value>;
      |                                                 ^~~~~~~~~~~~~~~~
$(SOURCE_ROOT)/contrib/libs/cxxsupp/libcxx/include/__functional/function.h:860:32: note: in instantiation of template type alias '_EnableIfLValueCallable' requested here
  860 |   template <class _Fp, class = _EnableIfLValueCallable<_Fp>>
      |                                ^
$(SOURCE_ROOT)/contrib/libs/cxxsupp/libcxx/include/__functional/function.h:861:25: note: in instanti
..[snippet truncated]..
 std::__invoke(std::forward<_Args>(__args)...);
      |                 ^
$(SOURCE_ROOT)/contrib/libs/cxxsupp/libcxx/include/__functional/function.h:169:22: note: in instantiation of function template specialization 'std::__invoke_void_return_wrapper<NThreading::TFuture<NCloud::NProto::TReleaseDevicesResponse>>::__call<(lambda at $(SOURCE_ROOT)/cloud/storage/core/libs/journalled_device_tcp_server/server_ut.cpp:411:13) &, NCloud::NProto::TReleaseDevicesRequest>' requested here
  169 |     return _Invoker::__call(__func_, std::forward<_ArgTypes>(__arg)...);
      |                      ^
$(SOURCE_ROOT)/contrib/libs/cxxsupp/libcxx/include/__functional/function.h:314:10: note: in instantiation of member function 'std::__function::__alloc_func<(lambda at $(SOURCE_ROOT)/cloud/storage/core/libs/journalled_device_tcp_server/server_ut.cpp:411:13), std::allocator<(lambda at $(SOURCE_ROOT)/cloud/storage/core/libs/journalled_device_tcp_server/server_ut.cpp:411:13)>, NThreading::TFuture<NCloud::NProto::TReleaseDevicesResponse> (NCloud::NProto::TReleaseDevicesRequest)>::operator()' requested here
  314 |   return __f_(std::forward<_ArgTypes>(__arg)...);
      |          ^
$(SOURCE_ROOT)/contrib/libs/cxxsupp/libcxx/include/__functional/function.h:269:34: note: in instantiation of member function 'std::__function::__func<(lambda at $(SOURCE_ROOT)/cloud/storage/core/libs/journalled_device_tcp_server/server_ut.cpp:411:13), std::allocator<(lambda at $(SOURCE_ROOT)/cloud/storage/core/libs/journalled_device_tcp_server/server_ut.cpp:411:13)>, NThreading::TFuture<NCloud::NProto::TReleaseDevicesResponse> (NCloud::NProto::TReleaseDevicesRequest)>::operator()' requested here
  269 |   _LIBCPP_HIDE_FROM_ABI explicit __func(_Fp&& __f, _Alloc&& __a) : __f_(std::move(__f), std::move(__a)) {}
      |                                  ^
$(SOURCE_ROOT)/contrib/libs/cxxsupp/libcxx/include/__functional/function.h:362:39: note: in instantiation of member function 'std::__function::__func<(lambda at $(SOURCE_ROOT)/cloud/storage/core/libs/journalled_device_tcp_server/server_ut.cpp:411:13), std::allocator<(lambda at $(SOURCE_ROOT)/cloud/storage/core/libs/journalled_device_tcp_server/server_ut.cpp:411:13)>, NThreading::TFuture<NCloud::NProto::TReleaseDevicesResponse> (NCloud::NProto::TReleaseDevicesRequest)>::__func' requested here
  362 |         __f_ = ::new ((void*)&__buf_) _Fun(std::move(__f), _Alloc(__af));
      |                                       ^
$(SOURCE_ROOT)/contrib/libs/cxxsupp/libcxx/include/__functional/function.h:373:60: note: in instantiation of function template specialization 'std::__function::__value_func<NThreading::TFuture<NCloud::NProto::TReleaseDevicesResponse> (NCloud::NProto::TReleaseDevicesRequest)>::__value_func<(lambda at $(SOURCE_ROOT)/cloud/storage/core/libs/journalled_device_tcp_server/server_ut.cpp:411:13), std::allocator<(lambda at $(SOURCE_ROOT)/cloud/storage/core/libs/journalled_device_tcp_server/server_ut.cpp:411:13)>>' requested here
  373 |   _LIBCPP_HIDE_FROM_ABI explicit __value_func(_Fp&& __f) : __value_func(std::forward<_Fp>(__f), allocator<_Fp>()) {}
      |                                                            ^
$(SOURCE_ROOT)/contrib/libs/cxxsupp/libcxx/include/__functional/function.h:947:50: note: in instantiation of function template specialization 'std::__function::__value_func<NThreading::TFuture<NCloud::NProto::TReleaseDevicesResponse> (NCloud::NProto::TReleaseDevicesRequest)>::__value_func<(lambda at $(SOURCE_ROOT)/cloud/storage/core/libs/journalled_device_tcp_server/server_ut.cpp:411:13), 0>' requested here
  947 | function<_Rp(_ArgTypes...)>::function(_Fp __f) : __f_(std::move(__f)) {}
      |                                                  ^
$(SOURCE_ROOT)/cloud/storage/core/libs/journalled_device_tcp_server/server_ut.cpp:411:13: note: in instantiation of function template specialization 'std::function<NThreading::TFuture<NCloud::NProto::TReleaseDevicesResponse> (NCloud::NProto::TReleaseDevicesRequest)>::function<(lambda at $(SOURCE_ROOT)/cloud/storage/core/libs/journalled_device_tcp_server/server_ut.cpp:411:13), void>' requested here
  411 |             [&](auto request)
      |             ^
$(SOURCE_ROOT)/cloud/storage/core/libs/journalled_device_tcp_server/server_ut.cpp:411:13: note: candidate template ignored: substitution failure [with request:auto = NCloud::NProto::TReleaseDevicesRequest]
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```