fix breakpad-sender (#4435)
fixing error introduced here
https://github.com/ydb-platform/nbs/pull/4272

```
2025-09-30 00:20:04,947 - ERROR - TypeError("Minidump.__init__() missing 1 required positional argument: 'gdb_timeout'")
```