fix: prevent running user-controlled code in pre-commit workflow (#7317)
`pull_request_target` allows us to fix "root" workflow code and prevent
user from launching arbitrary code (as `pull_request` does).

And in pre-commit workflow we had and reusable action used, which was
checked out from HEAD of user branch. Since pre-commit action is not
used anywhere else i decided to include its code to workflow itself,
instead, for example, checking out .github folder selectively and
replacing files.

Only thing we need to selectively check out this way is pre-commit
config itself to prevent user from modifying it

Error:
```
Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/actions-runner/_work/nbs/nbs/.github/actions/pre_commit'. Did you forget to run actions/checkout before running your local action?
```
Is expected since it checks out action from PR branch HEAD and it was
removed.