[libvhost bb->arc sync] Memory region sharing support
pytest/qemu: always zero memory before restarting the VM
Otherwise this starts to uncover all sorts of bugs caused by using
uninitialized memory. This time in SeaBIOS specifically but other
components can break in the future as well.
This test is supposed to check the vhost-user part of the stack, so focus
on that instead of failing because of bugs in other components.
Yandex-ST:
Signed-off-by: Daniil Tatianin <d-tatianin@yandex-team.ru>

memmap: make guest memory regions cacheable
We make use of the fact that we're passed an fd for every SET_MEM_TABLE
call, which we can use fstat(2) on to detect whether we alread have this
file descriptor mapped in. Store every mapped memory region in a list,
along with its inode and device ids, as well size and offset. On every
SET_MEM_TABLE call we iterate the region list and attempt to find an
existing mapping of this file descriptor, if one exists we simply
increment its refcount and reuse it without actually mapping anything.
This allows us to save a ton of address space as well as memory and page
fault traffic for VMs that have multiple disks connected to the same
server as we can reuse the same mapping for all disks.
Yandex-ST:
Signed-off-by: Daniil Tatianin <d-tatianin@yandex-team.ru>

memmap: move memory unmapping logic into vhd_memory_region
Since regions are now refcounted it only makes sense that the region
itself gets to decide when it no longer needs the memory.
Yandex-ST:
Signed-off-by: Daniil Tatianin <d-tatianin@yandex-team.ru>

memmap: make vhd_memory_region refcounted
So that we can share them between memmaps in the future commits.
Yandex-ST:
Signed-off-by: Daniil Tatianin <d-tatianin@yandex-team.ru>

memmap: move map/unmap callbacks into vhd_mmap_callbacks
So that we can share them in the following commits.
Yandex-ST:
Signed-off-by: Daniil Tatianin <d-tatianin@yandex-team.ru>

memmap: switch vhd_memory_map::regions to pointers
As we prepare to add the ability to reuse memory regions we need to be
able to store them as pointers so we can share them between different
vhd_memory_map structs in the future commits.
Yandex-ST:
Signed-off-by: Daniil Tatianin <d-tatianin@yandex-team.ru>

Remove the opaque argument from guest memory mapping callbacks
This was not used for anything by anyone, it also introduced additional
unneded complexities for further patches that make guest memory regions
cachable, so remove it.
Yandex-ST:
Signed-off-by: Daniil Tatianin <d-tatianin@yandex-team.ru>

pytest: introduce MultiDisk tests for aio-server backend
This runs the same test suite as before with the only difference being
that we have multiple vhost-user disks connected to the VM and served by
the server at the same time. This will be used to test the memory region
sharing functionality introduced in the following commits.
Yandex-ST:
Signed-off-by: Daniil Tatianin <d-tatianin@yandex-team.ru>

pytest/test_disk: rework SimpleVM/TestCommon to support multiple disks
This extends SimpleVM as well as related helpers to support multiple
disks.
Yandex-ST:
Signed-off-by: Daniil Tatianin <d-tatianin@yandex-team.ru>

pytest: make it possible for disk backends to support multiple disks
This reworks the curren Disk->Backend relationship and coupling so that
a backend can support multiple disks at the same time. In particular,
this makes it so every disk has an id associated with it that gets added
into the backend when a disk gets instantiated. All further disk to
backend communication happens via disk_id.
Yandex-ST:
Signed-off-by: Daniil Tatianin <d-tatianin@yandex-team.ru>

pytest/test_disk: factor out restart_test_disk
Make this a separate helper as we change the logic in the following
commits.
Yandex-ST:
Signed-off-by: Daniil Tatianin <d-tatianin@yandex-team.ru>

pytest: make image type be part of the Image tuple
That way we can get rid of a hack in VirtioDisk where it had to be
passed an explicit image type parameter in the constructor.
Yandex-ST:
Signed-off-by: Daniil Tatianin <d-tatianin@yandex-team.ru>

aio_server: add support for serving multiple disks
This is achieved by simply passing multiple -d/--disk arguments on the
command line.
Yandex-ST:
Signed-off-by: Daniil Tatianin <d-tatianin@yandex-team.ru>

aio_server: factor out disk stopping sequence into a separate function
So that it can be reused in the following commits. This also somewhat
improves readability.
Yandex-ST:
Signed-off-by: Daniil Tatianin <d-tatianin@yandex-team.ru>

aio_server: make vhd_stop_vhost_server the last step in the sequence
This makes the logic easier to factor out and shouldn't make any
functional differences as disk is unregisted beforehand anyway.
Yandex-ST:
Signed-off-by: Daniil Tatianin <d-tatianin@yandex-team.ru>

aio_server: factor out disk_start
This moves all the logic related to starting a disk into a separate
function so that it can be reused in the future commits.
Yandex-ST:
Signed-off-by: Daniil Tatianin <d-tatianin@yandex-team.ru>

aio_server: move server started log under create_threads
This makes more sense and also makes refactoring in the following
commits cleaner.
Yandex-ST:
Signed-off-by: Daniil Tatianin <d-tatianin@yandex-team.ru>

aio_server: improve user feedback for erroneous configuration
This reworks validate_disk_config so that it gives a unique error
message for every possible configuration error and/or missing option.
Yandex-ST:
Signed-off-by: Daniil Tatianin <d-tatianin@yandex-team.ru>

aio_server: add a VALUE_TO_STR macro helper
This will be used to build compile-time strings that contain
configurable values.
Yandex-ST:
Signed-off-by: Daniil Tatianin <d-tatianin@yandex-team.ru>

aio_server: factor out validate_disk_config
So that we can reuse this logic and further improve it in the future
commits.
Yandex-ST:
Signed-off-by: Daniil Tatianin <d-tatianin@yandex-team.ru>

aio_server: make disk_config part of disk
No reason to keep this outside of disk. This also allows us to remove a
redundant 'num_queues' field and makes further refactoring easier.
Yandex-ST:
Signed-off-by: Daniil Tatianin <d-tatianin@yandex-team.ru>

aio_server: remove monitor from disk_config
monitor is its own thing not related to disks, move it outside.
Yandex-ST:
Signed-off-by: Daniil Tatianin <d-tatianin@yandex-team.ru>

aio_server: merge aio_threads with disk
These two are almost always passed together and it doesn't really make
sense to keep them in separate places anyway.
Yandex-ST:
Signed-off-by: Daniil Tatianin <d-tatianin@yandex-team.ru>

aio_server: remove {submission,completion}_cb fields altogether
They aren't really needed as we always set them to the same value.
Yandex-ST:
Signed-off-by: Daniil Tatianin <d-tatianin@yandex-team.ru>

aio_server: rename backend -> disk, backend_config -> disk_config
Using generic words like backend & backend_config just make the code
harder to follow and understand. Rename to what they actually represent.
This also helps with the refactoring in the future commits.
Yandex-ST:
Signed-off-by: Daniil Tatianin <d-tatianin@yandex-team.ru>

aio_server: change command-line argument format
This changes the command-line argument format to be more like QEMU
'-device <args>', which allows us to extend the server to support
multiple disks in the future commits.
Yandex-ST:
Signed-off-by: Daniil Tatianin <d-tatianin@yandex-team.ru>

pytest/qemu/disks: move aio_server disk options to a separate struct
This makes further option refactoring more convenient and also allows us
to cleanly manage enabled options as actual class fields.
Yandex-ST:
Signed-off-by: Daniil Tatianin <d-tatianin@yandex-team.ru>

pytest/qemu/disks: move option formatting to a separate function
So that it can be overriden by subclasses in the following commits.
Yandex-ST:
Signed-off-by: Daniil Tatianin <d-tatianin@yandex-team.ru>

scripts/checkpath: stop recommending qemu_strto*
This is not QEMU so we don't have QEMU helpers.
Yandex-ST:
Signed-off-by: Daniil Tatianin <d-tatianin@yandex-team.ru>

aio_server: make all size types use unsigned long
This makes the code more consistent and simplifies error handling for
members where negative size doesn't make sense. It also allows us to
further refactor argument parsing in a less painful way.
Yandex-ST:
Signed-off-by: Daniil Tatianin <d-tatianin@yandex-team.ru>

scripts/ci_qemu_loader: always run apt update before loading versions
Otherwise we never end up getting the new releases as apt cache is never
updated.
Yandex-ST:
Signed-off-by: Daniil Tatianin <d-tatianin@yandex-team.ru>

pytest/qemu: support object-add for QEMU > 6.0
The format was changed in QEMU 6.0 removing the "props" key and instead
making all properties be top level.
Yandex-ST:
Signed-off-by: Daniil Tatianin <d-tatianin@yandex-team.ru>

pytest/qemu: specify an empty romfile
Otherwise its expected that we have very specific ROM packages installed
that provide ROMs with that exact size.
Signed-off-by: Daniil Tatianin <d-tatianin@yandex-team.ru>

pytest: change pytest version to 6.2.5
6.1.2 fails on ubuntu 22.04 with the following error:
      File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
      File "/home/d-tatianin/Work/libvhost-server/test/pytest/pytest_venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 162, in exec_module
        source_stat, co = _rewrite_test(fn, self.config)
      File "/home/d-tatianin/Work/libvhost-server/test/pytest/pytest_venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 359, in _rewrite_test
        co = compile(tree, fn_, "exec", dont_inherit=True)
    TypeError: required field "lineno" missing from alias
    make: *** [Makefile:42: pytest-fast] Error 1
Signed-off-by: Daniil Tatianin <d-tatianin@yandex-team.ru>

pytest: fix pytest version
Return previously stable version (6.1.2). It seems that between
6.1.x and 6.2.x return type of request.node() for "class" scope
was changed
Signed-off-by: Maksim Davydov <davydov-max@yandex-team.ru>

pytest: fix pytest version
On Focal pytest (7.4) fails bacause rep_setup not in node. Fix version
to return expected behaviour
Signed-off-by: Maksim Davydov <davydov-max@yandex-team.ru>