Fix testing client: add ListDiskStates method (#4382)
```
$(SOURCE_ROOT)/cloud/blockstore/public/sdk/go/client/discovery_test.go:166:9: cannot use &testClient{…} (value of type *testClient) as ClientIface value in return statement: *testClient does not implement ClientIface (missing method ListDiskStates)
```