Make f2c generated outputs depend on f2c.h
```
contrib/python/scipy/py3/_/scipy/fftpack/src/dfftpack/dsinti.f.c:22:10: fatal error: 'f2c.h' file not found
#include "f2c.h"
         ^~~~~~~
1 error generated.
```