importing silk (#5930)
### Notes
Importing https://github.com/ClickHouse/silk - it's a fiber scheduler.
Will use it to implement https://github.com/ydb-platform/nbs/issues/5895

Includes a patch for librseq because otherwise its build fails:
```
~/git/nbs/contrib/libs/librseq$ ~/git/nbs/ya make -d -j 4
------- [CC] {FAILED} $(S)/contrib/libs/librseq/src/rseq-mempool.c
...
~/git/nbs/contrib/libs/librseq/src/rseq-mempool.c:716:26: error: use of undeclared identifier 'MFD_CLOEXEC'
        fd = memfd_create(name, MFD_CLOEXEC);
                                ^
~/git/nbs/contrib/libs/librseq/src/rseq-mempool.c:815:34: error: use of undeclared identifier 'MADV_WIPEONFORK'
                if (madvise(header, page_size, MADV_WIPEONFORK))
                                               ^
2 errors generated.
Failed

```

### Issue
https://github.com/ydb-platform/nbs/issues/5895